mongock:
  migration-scan-package: VSDS
springdoc:
  swagger-ui:
    path: /v1/swagger
management:
  tracing:
    enabled: false
ldes-server:
  host-name: http://localhost:8080
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://ldes-mongodb:27017/traffic-data
